connect duckdb

In [ ]:
import duckdb

conn = duckdb.connect("sakila.duckdb")

# determine the maximum number of rows DuckDB will
# sample from a Pandas DataFrame when automatically analyzing its schema
conn.sql("SET pandas_analyze_sample=100000;")

In [ ]:
#  Which movies are longer than 3 hours (180 minutes), show the title and its length?
 
conn.sql("""select * from staging.film
         where length > 180
         """).df()


here i use regex match

In [62]:
# "love" is not included in any title

conn.sql(""" select title, rating, length,
         description from staging.film
         where regexp_matches(title, 'love') ;
         
         """).df()

Empty DataFrame
Columns: [title, rating, length, description]
Index: []

In [ ]:
""" Calculate descriptive statistics on the length column, The Manager wants, shortest, average, median and
longest movie length """

conn.sql("""
         select
            min(length) as "shortest movie",
            avg(length) as "average length of all movies",
            median(length) as "median length of all movies",
            max(length) as "longest movie"
             
         from staging.film
         """).df()

,shortest movie,average length of all movies,median length of all movies,longest movie
0,46,115.272,114.0,185

In [77]:
"""d) The rental rate is the cost to rent a movie and the rental duration is the number of days a customer can
keep the movie. The Manager wants to know the 10 most expensive movies to rent per day."""

# kostnad genom tiden

conn.sql(""" 
         select
            title,
            rental_rate/rental_duration as "cost_per_day($)"
            
        from staging.film
        order by "cost_per_day($)" desc
        limit 10

         """).df()

                 title  cost_per_day($)
0       ACE GOLDFINGER         1.663333
1      AMERICAN CIRCUS         1.663333
2          AUTUMN CROW         1.663333
3  BACKLASH UNDEFEATED         1.663333
4      BEAST HUNCHBACK         1.663333
5     BEHAVIOR RUNAWAY         1.663333
6      BILKO ANONYMOUS         1.663333
7    CARIBBEAN LIBERTY         1.663333
8     CASPER DRAGONFLY         1.663333
9    CASUALTIES ENCINO         1.663333